version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - graylog-net
    volumes:
      - mongodb_data:/data/db

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx1g
      - plugins.security.ssl.http.enabled=false
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=SomePasswordPepper123#
    networks:
      - graylog-net
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  graylog:
    image: graylog/graylog:5.2
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_HTTP_EXTERNAL_URI=http://0.0.0.0:9000/
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
      - GRAYLOG_ROOT_PASSWORD_SHA2=aea3cc31f52ba4b24b56d2d9f3652b17818de6fe6f249c7640e345bfd58c08f4
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
      #- GRAYLOG_ROOT_TIMEZONE=America/Guayaquil
    ports:
      - 9000:9000
      - 514:514
      - 514:514/udp
      - 4514:4514
      - 4514:4514/udp
      - 5514:5514
      - 5514:5514/udp
      - 6514:6514
      - 6514:6514/udp
      - 7514:7514
      - 7514:7514/udp
    networks:
      - graylog-net
    depends_on:
      - mongodb
      - opensearch
    volumes:
      - graylog_data:/usr/share/graylog/data
      - graylog_logs:/var/log/graylog

networks:
  graylog-net:
    driver: bridge

volumes:
  mongodb_data:
  opensearch_data:
  graylog_data:
  graylog_logs:
